<?php
/*//////////////////////////////////////////////////////////
// ######################################################///
// # DuhokForum 1.1                                     # //
// ###################################################### //
// #                                                    # //
// #       --  DUHOK FORUM IS FREE SOFTWARE  --         # //
// #                                                    # //
// #   ========= Programming By Dilovan ==============  # //
// # Copyright © 2007-2009 Dilovan. All Rights Reserved # //
// #----------------------------------------------------# //
// #----------------------------------------------------# //
// # If you want any support vist down address:-        # //
// # Email: df@duhoktimes.com                           # //
// # Site: http://df.duhoktimes.com/index.php           # //
// ###################################################### //
//////////////////////////////////////////////////////////*/

                    echo'
                    <option value="" '.check_select($selected, "").'>-- غير محددة --</option>
					<option value="إثيوبيا" '.check_select($selected, "إثيوبيا").'>إثيوبيا</option>
					<option value="إذربيجان" '.check_select($selected, "إذربيجان").'>إذربيجان</option>
					<option value="أرمينيا" '.check_select($selected, "أرمينيا").'>أرمينيا</option>
					<option value="إريتريا" '.check_select($selected, "إريتريا").'>إريتريا</option>
					<option value="أزبكستان" '.check_select($selected, "أزبكستان").'>أزبكستان</option>
					<option value="أسبانيا" '.check_select($selected, "أسبانيا").'>أسبانيا</option>
					<option value="أستراليا" '.check_select($selected, "أستراليا").'>أستراليا</option>
					<option value="إستونيا" '.check_select($selected, "إستونيا").'>إستونيا</option>
					<option value="إسكوتلندا" '.check_select($selected, "إسكوتلندا").'>إسكوتلندا</option>
					<option value="أفغانستان" '.check_select($selected, "أفغانستان").'>أفغانستان</option>
					<option value="ألبانيا" '.check_select($selected, "ألبانيا").'>ألبانيا</option>
					<option value="ألمانيا" '.check_select($selected, "ألمانيا").'>ألمانيا</option>
					<option value="ألمانيا الشرقية" '.check_select($selected, "ألمانيا الشرقية").'>ألمانيا الشرقية</option>
					<option value="أنتيجا وبربودا" '.check_select($selected, "أنتيجا وبربودا").'>أنتيجا وبربودا</option>
					<option value="إنجلترا" '.check_select($selected, "إنجلترا").'>إنجلترا</option>
					<option value="أنجيلا" '.check_select($selected, "أنجيلا").'>أنجيلا</option>
					<option value="أندورا" '.check_select($selected, "أندورا").'>أندورا</option>
					<option value="إندونيسيا" '.check_select($selected, "إندونيسيا").'>إندونيسيا</option>
					<option value="أنغولا" '.check_select($selected, "أنغولا").'>أنغولا</option>
					<option value="أوروجواي" '.check_select($selected, "أوروجواي").'>أوروجواي</option>
					<option value="أوغندا" '.check_select($selected, "أوغندا").'>أوغندا</option>
					<option value="أوكرانيا" '.check_select($selected, "أوكرانيا").'>أوكرانيا</option>
					<option value="إيران" '.check_select($selected, "إيران").'>إيران</option>
					<option value="إيرلندا" '.check_select($selected, "إيرلندا").'>إيرلندا</option>
					<option value="إيرلندا الشمالية" '.check_select($selected, "إيرلندا الشمالية").'>إيرلندا الشمالية</option>
					<option value="أيسلندا" '.check_select($selected, "أيسلندا").'>أيسلندا</option>
					<option value="إيطاليا" '.check_select($selected, "إيطاليا").'>إيطاليا</option>
					<option value="الإتحاد السوفيتي" '.check_select($selected, "الإتحاد السوفيتي").'>الإتحاد السوفيتي</option>
					<option value="الأرجنتين" '.check_select($selected, "الأرجنتين").'>الأرجنتين</option>
					<option value="الأردن" '.check_select($selected, "الأردن").'>الأردن</option>
					<option value="الإكوادور" '.check_select($selected, "الإكوادور").'>الإكوادور</option>
					<option value="الإمارات" '.check_select($selected, "الإمارات").'>الإمارات</option>
					<option value="البحرين" '.check_select($selected, "البحرين").'>البحرين</option>
					<option value="البرازيل" '.check_select($selected, "البرازيل").'>البرازيل</option>
					<option value="البرتغال" '.check_select($selected, "البرتغال").'>البرتغال</option>
					<option value="البهاما" '.check_select($selected, "البهاما").'>البهاما</option>
					<option value="البوسنة والهرسك" '.check_select($selected, "البوسنة والهرسك").'>البوسنة والهرسك</option>
					<option value="التشيك" '.check_select($selected, "التشيك").'>التشيك</option>
					<option value="الجابون" '.check_select($selected, "الجابون").'>الجابون</option>
					<option value="الجزائر" '.check_select($selected, "الجزائر").'>الجزائر</option>
					<option value="الدانمارك" '.check_select($selected, "الدانمارك").'>الدانمارك</option>
					<option value="الدومينيكان" '.check_select($selected, "الدومينيكان").'>الدومينيكان</option>
					<option value="الساموا الأمريكية" '.check_select($selected, "الساموا الأمريكية").'>الساموا الأمريكية</option>
					<option value="السعودية" '.check_select($selected, "السعودية").'>السعودية</option>
					<option value="السلفادور" '.check_select($selected, "السلفادور").'>السلفادور</option>
					<option value="السنغال" '.check_select($selected, "السنغال").'>السنغال</option>
					<option value="السودان" '.check_select($selected, "السودان").'>السودان</option>
					<option value="السويد" '.check_select($selected, "السويد").'>السويد</option>
					<option value="السيشيل" '.check_select($selected, "السيشيل").'>السيشيل</option>
					<option value="الصومال" '.check_select($selected, "الصومال").'>الصومال</option>
					<option value="الصين" '.check_select($selected, "الصين").'>الصين</option>
					<option value="العراق" '.check_select($selected, "العراق").'>العراق</option>
					<option value="الفلبين" '.check_select($selected, "الفلبين").'>الفلبين</option>
					<option value="الكاميرون" '.check_select($selected, "الكاميرون").'>الكاميرون</option>
					<option value="الكونجو" '.check_select($selected, "الكونجو").'>الكونجو</option>
					<option value="الكويت" '.check_select($selected, "الكويت").'>الكويت</option>
					<option value="المجر" '.check_select($selected, "المجر").'>المجر</option>
					<option value="المغرب" '.check_select($selected, "المغرب").'>المغرب</option>
					<option value="المكسيك" '.check_select($selected, "المكسيك").'>المكسيك</option>
					<option value="الموريشيس" '.check_select($selected, "الموريشيس").'>الموريشيس</option>
					<option value="النرويج" '.check_select($selected, "النرويج").'>النرويج</option>
					<option value="النمسا" '.check_select($selected, "النمسا").'>النمسا</option>
					<option value="النيبال" '.check_select($selected, "النيبال").'>النيبال</option>
					<option value="النيجر" '.check_select($selected, "النيجر").'>النيجر</option>
					<option value="الهند" '.check_select($selected, "الهند").'>الهند</option>
					<option value="الهوندوراس" '.check_select($selected, "الهوندوراس").'>الهوندوراس</option>
					<option value="الولايات المتحدة الأمريكية" '.check_select($selected, "الولايات المتحدة الأمريكية").'>الولايات المتحدة الأمريكية</option>
					<option value="اليابان" '.check_select($selected, "اليابان").'>اليابان</option>
					<option value="اليمن" '.check_select($selected, "اليمن").'>اليمن</option>
					<option value="اليونان" '.check_select($selected, "اليونان").'>اليونان</option>
					<option value="انتاركتيكا" '.check_select($selected, "انتاركتيكا").'>انتاركتيكا</option>
					<option value="بابوا نيو جيني" '.check_select($selected, "بابوا نيو جيني").'>بابوا نيو جيني</option>
					<option value="باراجواي" '.check_select($selected, " ").'>باراجواي</option>
					<option value="باكستان" '.check_select($selected, " ").'>باكستان</option>
					<option value="بالاو" '.check_select($selected, " ").'>بالاو</option>
					<option value="بربادوس" '.check_select($selected, " ").'>بربادوس</option>
					<option value="برمودا" '.check_select($selected, " ").'>برمود</option>
					<option value="بروناي دار السلام" '.check_select($selected, " ").'>بروناي دار السلام</option>
					<option value="بريطانيا" '.check_select($selected, " ").'>بريطاني</option>
					<option value="بلجيكا" '.check_select($selected, " ").'>بلجيك</option>
					<option value="بلغاريا" '.check_select($selected, " ").'>بلغاري</option>
					<option value="بليز" '.check_select($selected, " ").'>بليز</option>
					<option value="بنغلادش" '.check_select($selected, " ").'>بنغلادش</option>
					<option value="بنما" '.check_select($selected, " ").'>بنم</option>
					<option value="بنين" '.check_select($selected, " ").'>بنين</option>
					<option value="بوتان" '.check_select($selected, " ").'>بوتان</option>
					<option value="بوتسوانا" '.check_select($selected, " ").'>بوتسوان</option>
					<option value="بورتو ريكو" '.check_select($selected, " ").'>بورتو ريكو</option>
					<option value="بوركينا فاسو" '.check_select($selected, " ").'>بوركينا فاسو</option>
					<option value="بوروندي" '.check_select($selected, " ").'>بوروندي</option>
					<option value="بولندا" '.check_select($selected, " ").'>بولند</option>
					<option value="بوليفيا" '.check_select($selected, " ").'>بوليفي</option>
					<option value="بولينيسيا الفرنسية" '.check_select($selected, " ").'>بولينيسيا الفرنسية</option>
					<option value="بيرو" '.check_select($selected, " ").'>بيرو</option>
					<option value="تاطجكستان" '.check_select($selected, " ").'>تاطجكستان</option>
					<option value="تايلاند" '.check_select($selected, " ").'>تايلاند</option>
					<option value="تايوان" '.check_select($selected, " ").'>تايوان</option>
					<option value="تركمنستان" '.check_select($selected, " ").'>تركمنستان</option>
					<option value="تركيا" '.check_select($selected, " ").'>تركي</option>
					<option value="ترينيداد وتوباجو" '.check_select($selected, " ").'>ترينيداد وتوباجو</option>
					<option value="تشاد" '.check_select($selected, " ").'>تشاد</option>
					<option value="تشيكوسلوفاكيا" '.check_select($selected, " ").'>تشيكوسلوفاكي</option>
					<option value="تشيلي" '.check_select($selected, " ").'>تشيلي</option>
					<option value="تنزانيا" '.check_select($selected, " ").'>تنزاني</option>
					<option value="توجو" '.check_select($selected, " ").'>توجو</option>
					<option value="توفالو" '.check_select($selected, " ").'>توفالو</option>
					<option value="تونجا" '.check_select($selected, " ").'>تونج</option>
					<option value="تونس" '.check_select($selected, " ").'>تونس</option>
					<option value="تيمور الشرقية" '.check_select($selected, " ").'>تيمور الشرقية</option>
					<option value="جامبيا" '.check_select($selected, " ").'>جامبي</option>
					<option value="جاميكا" '.check_select($selected, " ").'>جاميك</option>
					<option value="جبل طارق" '.check_select($selected, " ").'>جبل طارق</option>
					<option value="جرنادا" '.check_select($selected, " ").'>جرناد</option>
					<option value="جزر الأنتيل" '.check_select($selected, " ").'>جزر الأنتيل</option>
					<option value="جزر الرينيون" '.check_select($selected, " ").'>جزر الرينيون</option>
					<option value="جزر السولومون" '.check_select($selected, " ").'>جزر السولومون</option>
					<option value="جزر الفلكلاند" '.check_select($selected, " ").'>جزر الفلكلاند</option>
					<option value="جزر القمر" '.check_select($selected, " ").'>جزر القمر</option>
					<option value="جزر الكايمان" '.check_select($selected, " ").'>جزر الكايمان</option>
					<option value="جزر الكوكوس" '.check_select($selected, " ").'>جزر الكوكوس</option>
					<option value="جزر المارشال" '.check_select($selected, " ").'>جزر المارشال</option>
					<option value="جزر المالديف" '.check_select($selected, " ").'>جزر المالديف</option>
					<option value="جزر جرينلاند" '.check_select($selected, " ").'>جزر جرينلاند</option>
					<option value="جزر فاروه" '.check_select($selected, " ").'>جزر فاروه</option>
					<option value="جزر فيجي" '.check_select($selected, " ").'>جزر فيجي</option>
					<option value="جزر كوك" '.check_select($selected, " ").'>جزر كوك</option>
					<option value="جزيرة بوفيه" '.check_select($selected, " ").'>جزيرة بوفيه</option>
					<option value="جمهورية أفريقيا الوسطى" '.check_select($selected, " ").'>جمهورية أفريقيا الوسطى</option>
					<option value="جمهورية الكونجو" '.check_select($selected, " ").'>جمهورية الكونجو</option>
					<option value="جنوب أفريقيا" '.check_select($selected, " ").'>جنوب أفريقي</option>
					<option value="جواتيمالا" '.check_select($selected, " ").'>جواتيمال</option>
					<option value="جوادلوب" '.check_select($selected, " ").'>جوادلوب</option>
					<option value="جوام" '.check_select($selected, " ").'>جوام</option>
					<option value="جورجيا" '.check_select($selected, " ").'>جورجي</option>
					<option value="جيبوتي" '.check_select($selected, " ").'>جيبوتي</option>
					<option value="جينيا بيساو" '.check_select($selected, " ").'>جينيا بيساو</option>
					<option value="دومينيكا" '.check_select($selected, " ").'>دومينيك</option>
					<option value="رواندا" '.check_select($selected, " ").'>رواند</option>
					<option value="روسيا" '.check_select($selected, " ").'>روسي</option>
					<option value="روسيا البيضاء" '.check_select($selected, " ").'>روسيا البيضاء</option>
					<option value="رومانيا" '.check_select($selected, " ").'>روماني</option>
					<option value="زامبيا" '.check_select($selected, " ").'>زامبي</option>
					<option value="زمبابوي" '.check_select($selected, " ").'>زمبابوي</option>
					<option value="ساحل العاج" '.check_select($selected, " ").'>ساحل العاج</option>
					<option value="ساموا" '.check_select($selected, " ").'>سامو</option>
					<option value="سان مارينو" '.check_select($selected, " ").'>سان مارينو</option>
					<option value="سانت لوسيا" '.check_select($selected, " ").'>سانت لوسي</option>
					<option value="سري لانكا" '.check_select($selected, " ").'>سري لانك</option>
					<option value="سلوفاكيا" '.check_select($selected, " ").'>سلوفاكي</option>
					<option value="سلوفينيا" '.check_select($selected, " ").'>سلوفيني</option>
					<option value="سنغافورة" '.check_select($selected, " ").'>سنغافورة</option>
					<option value="سوازيلاند" '.check_select($selected, " ").'>سوازيلاند</option>
					<option value="سوريا" '.check_select($selected, " ").'>سوري</option>
					<option value="سورينام" '.check_select($selected, " ").'>سورينام</option>
					<option value="سويسرا" '.check_select($selected, " ").'>سويسر</option>
					<option value="سييرا ليون" '.check_select($selected, " ").'>سييرا ليون</option>
					<option value="صربيا" '.check_select($selected, " ").'>صربي</option>
					<option value="عمان" '.check_select($selected, " ").'>عمان</option>
					<option value="غانا" '.check_select($selected, " ").'>غان</option>
					<option value="غيانا" '.check_select($selected, " ").'>غيان</option>
					<option value="غيانا الفرنسية" '.check_select($selected, " ").'>غيانا الفرنسية</option>
					<option value="غينيا" '.check_select($selected, " ").'>غيني</option>
					<option value="غينيا الإستوائية" '.check_select($selected, " ").'>غينيا الإستوائية</option>
					<option value="فاناتو" '.check_select($selected, " ").'>فاناتو</option>
					<option value="فرنسا" '.check_select($selected, " ").'>فرنس</option>
					<option value="فلسطين" '.check_select($selected, " ").'>فلسطين</option>
					<option value="فنزويلا" '.check_select($selected, " ").'>فنزويل</option>
					<option value="فنلندا" '.check_select($selected, " ").'>فنلند</option>
					<option value="فيتنام" '.check_select($selected, " ").'>فيتنام</option>
					<option value="قبرص" '.check_select($selected, " ").'>قبرص</option>
					<option value="قطر" '.check_select($selected, " ").'>قطر</option>
					<option value="كاب فيردي" '.check_select($selected, " ").'>كاب فيردي</option>
					<option value="كازاخستان" '.check_select($selected, " ").'>كازاخستان</option>
					<option value="كاليدونيا الجديدة" '.check_select($selected, " ").'>كاليدونيا الجديدة</option>
					<option value="كرواتيا" '.check_select($selected, " ").'>كرواتي</option>
					<option value="كمبوديا" '.check_select($selected, " ").'>كمبودي</option>
					<option value="كندا" '.check_select($selected, " ").'>كند</option>
					<option value="كوبا" '.check_select($selected, " ").'>كوب</option>
					<option value="كوريا الجنوبية" '.check_select($selected, " ").'>كوريا الجنوبية</option>
					<option value="كوريا الشمالية" '.check_select($selected, " ").'>كوريا الشمالية</option>
					<option value="كوستا ريكا" '.check_select($selected, " ").'>كوستا ريك</option>
					<option value="كولمبيا" '.check_select($selected, " ").'>كولمبي</option>
					<option value="كيرجيستان" '.check_select($selected, " ").'>كيرجيستان</option>
					<option value="كيريباتي" '.check_select($selected, " ").'>كيريباتي</option>
					<option value="كينيا" '.check_select($selected, " ").'>كيني</option>
					<option value="لاتفيا" '.check_select($selected, " ").'>لاتفي</option>
					<option value="لاوس" '.check_select($selected, " ").'>لاوس</option>
					<option value="لبنان" '.check_select($selected, " ").'>لبنان</option>
					<option value="لوكسمبرج" '.check_select($selected, " ").'>لوكسمبرج</option>
					<option value="ليبيا" '.check_select($selected, " ").'>ليبي</option>
					<option value="ليبيريا" '.check_select($selected, " ").'>ليبيري</option>
					<option value="ليثوانيا" '.check_select($selected, " ").'>ليثواني</option>
					<option value="ليسوثو" '.check_select($selected, " ").'>ليسوثو</option>
					<option value="ليشتنشتين" '.check_select($selected, " ").'>ليشتنشتين</option>
					<option value="مارتينيك" '.check_select($selected, " ").'>مارتينيك</option>
					<option value="ماكاو" '.check_select($selected, " ").'>ماكاو</option>
					<option value="مالاوي" '.check_select($selected, " ").'>مالاوي</option>
					<option value="مالطة" '.check_select($selected, " ").'>مالطة</option>
					<option value="مالي" '.check_select($selected, " ").'>مالي</option>
					<option value="ماليزيا" '.check_select($selected, " ").'>ماليزي</option>
					<option value="مايكرونيسيا" '.check_select($selected, " ").'>مايكرونيسي</option>
					<option value="مدغشقر" '.check_select($selected, " ").'>مدغشقر</option>
					<option value="مصر" '.check_select($selected, " ").'>مصر</option>
					<option value="مقدونيا" '.check_select($selected, " ").'>مقدوني</option>
					<option value="موريتانيا" '.check_select($selected, "موريتانيا").'>موريتانيا</option>
					<option value="موزمبيق" '.check_select($selected, "موزمبيق").'>موزمبيق</option>
					<option value="مولدوفا" '.check_select($selected, "مولدوفا").'>مولدوفا</option>
					<option value="موناكو" '.check_select($selected, "موناكو").'>موناكو</option>
					<option value="مونسرات" '.check_select($selected, "مونسرات").'>مونسرات</option>
					<option value="مونغوليا" '.check_select($selected, "مونغوليا").'>مونغوليا</option>
					<option value="ميانمار" '.check_select($selected, "ميانمار").'>ميانمار</option>
					<option value="ناميبيا" '.check_select($selected, "ناميبيا").'>ناميبيا</option>
					<option value="ناورو" '.check_select($selected, "ناورو").'>ناورو</option>
					<option value="نوي" '.check_select($selected, "نوي").'>نوي</option>
					<option value="نيجيريا" '.check_select($selected, "نيجيريا").'>نيجيريا</option>
					<option value="نيكاراجوا" '.check_select($selected, "نيكاراجوا").'>نيكاراجوا</option>
					<option value="نيو زيلندا" '.check_select($selected, "نيو زيلندا").'>نيو زيلندا</option>
					<option value="هايتي" '.check_select($selected, "هايتي").'>هايتي</option>
					<option value="هولندا" '.check_select($selected, "هولندا").'>هولندا</option>
					<option value="هونج كونج" '.check_select($selected, "هونج كونج").'>هونج كونج</option>
					<option value="ويلز" '.check_select($selected, "ويلز").'>ويلز</option>
					<option value="يوغوسلافيا" '.check_select($selected, "يوغوسلافيا").'>يوغوسلافيا</option>';
?>
